name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Update Server
        run: ssh root@flick.photos "~/files/scripts/update.sh"

      - name: Deploy API
        run: ssh root@flick.photos "~/files/scripts/api.sh"

      - name: Deploy API Docs
        run: ssh root@flick.photos "~/files/scripts/api.sh"

      - name: Deploy Web
        run: ssh root@flick.photos "~/files/scripts/api.sh"
