name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  UpdateRepos:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Update Repos
        run: ssh root@flick.photos "~/files/scripts/update.sh"

  DeployAPI:
    runs-on: ubuntu-latest
    needs: UpdateRepos

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build API
        run: ssh root@flick.photos "~/files/scripts/api-build.sh"

      - name: Test API
        run: ssh root@flick.photos "~/files/scripts/api-test.sh"

      - name: Deploy API
        run: ssh root@flick.photos "~/files/scripts/api-deploy.sh"

  DeployAPIDocs:
    runs-on: ubuntu-latest
    needs: UpdateRepos

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build API Docs
        run: ssh root@flick.photos "~/files/scripts/apidocs-build.sh"

      - name: Test API Docs
        run: ssh root@flick.photos "~/files/scripts/apidocs-test.sh"

      - name: Deploy API Docs
        run: ssh root@flick.photos "~/files/scripts/apidocs-deploy.sh"

  DeployWeb:
    runs-on: ubuntu-latest
    needs: UpdateRepos

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Build Web
        run: ssh root@flick.photos "~/files/scripts/web-build.sh"

      - name: Test Web
        run: ssh root@flick.photos "~/files/scripts/web-test.sh"

      - name: Deploy Web
        run: ssh root@flick.photos "~/files/scripts/web-deploy.sh"
