name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H flick.photos >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh root@flick.photos "~/files/scripts/deploy.sh"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
